package com.hoang.crypto.entity;

import com.hoang.crypto.constant.CryptoPair;
import com.hoang.crypto.constant.Currency;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class EntityTest {

    @Test
    void testUserEntity() {
        // Arrange & Act
        User user = new User("testuser", "test@example.com", "password");

        // Assert
        assertEquals("testuser", user.getUsername());
        assertEquals("test@example.com", user.getEmail());
        assertEquals("password", user.getPassword());
        assertNull(user.getId()); // ID is generated by database
        assertTrue(user.getRoles().isEmpty());
    }

    @Test
    void testWalletEntity() {
        // Arrange
        User user = new User("testuser", "test@example.com", "password");
        user.setId(1L);
        Wallet wallet = new Wallet();
        wallet.setUser(user);
        wallet.setCurrency(Currency.USDT);
        wallet.setBalance(new BigDecimal("1000.50"));

        // Act & Assert
        assertEquals(user, wallet.getUser());
        assertEquals(Currency.USDT, wallet.getCurrency());
        assertEquals(0, new BigDecimal("1000.50").compareTo(wallet.getBalance()));
        assertNull(wallet.getId()); // ID is generated by database
    }

    @Test
    void testTransactionEntity() {
        // Arrange
        User user = new User("testuser", "test@example.com", "password");
        user.setId(1L);
        Transaction transaction = new Transaction();
        transaction.setUser(user);
        transaction.setPair(CryptoPair.BTCUSDT);
        transaction.setType("BUY");
        transaction.setPrice(new BigDecimal("50000.00"));
        transaction.setAmount(new BigDecimal("0.1"));
        transaction.setTimestamp(LocalDateTime.now());

        // Act & Assert
        assertEquals(user, transaction.getUser());
        assertEquals(CryptoPair.BTCUSDT, transaction.getPair());
        assertEquals("BUY", transaction.getType());
        assertEquals(0, new BigDecimal("50000.00").compareTo(transaction.getPrice()));
        assertEquals(0, new BigDecimal("0.1").compareTo(transaction.getAmount()));
        assertNotNull(transaction.getTimestamp());
        assertNull(transaction.getId()); // ID is generated by database
    }

    @Test
    void testPriceAggregateEntity() {
        // Arrange
        PriceAggregate price = new PriceAggregate();
        price.setPair(CryptoPair.ETHUSDT);
        price.setBid(new BigDecimal("2000.00"));
        price.setAsk(new BigDecimal("2001.00"));
        price.setTimestamp(LocalDateTime.now());

        // Act & Assert
        assertEquals(CryptoPair.ETHUSDT, price.getPair());
        assertEquals(0, new BigDecimal("2000.00").compareTo(price.getBid()));
        assertEquals(0, new BigDecimal("2001.00").compareTo(price.getAsk()));
        assertNotNull(price.getTimestamp());
        assertNull(price.getId()); // ID is generated by database
    }

    @Test
    void testTradeRequestEntity() {
        // Arrange & Act
        TradeRequest request = new TradeRequest();
        request.setPair(CryptoPair.BTCUSDT);
        request.setType("SELL");
        request.setAmount(new BigDecimal("0.05"));

        // Assert
        assertEquals(CryptoPair.BTCUSDT, request.getPair());
        assertEquals("SELL", request.getType());
        assertEquals(0, new BigDecimal("0.05").compareTo(request.getAmount()));
    }

    @Test
    void testRoleEntity() {
        // Arrange & Act
        Role role = new Role();
        role.setId(1);
        role.setName(ERole.ROLE_USER);

        // Assert
        assertEquals(Integer.valueOf(1), role.getId());
        assertEquals(ERole.ROLE_USER, role.getName());
    }
}
