-- Create T_ROLE table
CREATE TABLE T_ROLE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

-- Create T_USER table
CREATE TABLE T_USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL
);

-- Create T_USER_ROLE join table
CREATE TABLE T_USER_ROLE (
    user_id BIGINT NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES T_USER(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES T_ROLE(id) ON DELETE CASCADE
);

-- Create T_REFRESH_TOKEN table
CREATE TABLE T_REFRESH_TOKEN (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES T_USER(id) ON DELETE CASCADE
);

-- Create T_WALLET table
CREATE TABLE T_WALLET (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL,
    balance DECIMAL(19, 8) NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES T_USER(id) ON DELETE CASCADE
);

-- Create T_TRANSACTION table
CREATE TABLE T_TRANSACTION (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(10) NOT NULL,
    pair VARCHAR(10) NOT NULL,
    price DECIMAL(19, 8) NOT NULL,
    amount DECIMAL(19, 8) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES T_USER(id) ON DELETE CASCADE
);

-- Create T_PRICE_AGGREGATE table
CREATE TABLE T_PRICE_AGGREGATE (
    id UUID PRIMARY KEY,
    pair VARCHAR(20) NOT NULL,
    bid DECIMAL(20, 8) NOT NULL,
    ask DECIMAL(20, 8) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

-- Create sequences for auto-generated primary keys
CREATE SEQUENCE t_role_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE t_user_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE t_refresh_token_seq START WITH 1 INCREMENT BY 50;

-- Insert default roles
INSERT INTO T_ROLE (name) VALUES ('ROLE_USER'), ('ROLE_MODERATOR'), ('ROLE_ADMIN');
